branches:
  only:
    - master

configuration: Release

build:
  - cmd: .\psake.bat ci
  
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    on:
      appveyor_repo_tag: true
      