branches:
  only:
    - master

configuration: Release

build:
  project: src\Steam.Models.sln
  publish_nuget: true
  include_nuget_references: true
  
before_build:
  - cmd: nuget restore src\Steam.Models.sln
  
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    on:
      appveyor_repo_tag: true
      