version: '{build}'  

pull_requests:  
  do_not_increment_build_number: true
  
branches:  
  only:
  - master
  
nuget:  
  disable_publish_on_pr: true
  
build_script:
  - cmd: .\psake.bat ci
  
test: off  

artifacts:  
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    on:
      branch: master
      appveyor_repo_tag: true